package io.github.wj9806.minicat.core.event;

/**
 * 定义事件类型
 */
public enum EventType {
    SERVLET_CONTEXT_INITIALIZED,
    SERVLET_CONTEXT_DESTROYED,

    SERVLET_CONTEXT_ATTRIBUTE_ADDED,
    SERVLET_CONTEXT_ATTRIBUTE_REMOVED,
    SERVLET_CONTEXT_ATTRIBUTE_REPLACED,

    SERVLET_REQUEST_DESTROYED,
    SERVLET_REQUEST_INITIALIZED,

    SERVLET_REQUEST_ATTRIBUTE_ADDED,
    SERVLET_REQUEST_ATTRIBUTE_REMOVED,
    SERVLET_REQUEST_ATTRIBUTE_REPLACED,

    SESSION_CREATED,
    SESSION_DESTROYED,

    SESSION_ATTRIBUTE_ADDED,
    SESSION_ATTRIBUTE_REMOVED,
    SESSION_ATTRIBUTE_REPLACED,

    SESSION_VALUE_BOUND,
    SESSION_VALUE_UNBOUND,
    SESSION_ID_CHANGED
}
